// <auto-generated />
using System;
using MessageList.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MessageList.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210319110128_Added_Roles")]
    partial class Added_Roles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MessageList.Models.AudioFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasMaxLength(20500000)
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<int>("FileCollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("related_file_collection_id");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long>("Length")
                        .HasColumnType("bigint")
                        .HasColumnName("length");

                    b.HasKey("Id");

                    b.HasIndex("FileCollectionId");

                    b.ToTable("audio");
                });

            modelBuilder.Entity("MessageList.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FeedbackContacts")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("feedback_contacts");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("feedback_text");

                    b.HasKey("Id");

                    b.ToTable("feedbacks");
                });

            modelBuilder.Entity("MessageList.Models.FileCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("related_message_id");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("file_collections");
                });

            modelBuilder.Entity("MessageList.Models.ImageFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasMaxLength(1050000)
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<int>("FileCollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("related_file_collection_id");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long>("Length")
                        .HasColumnType("bigint")
                        .HasColumnName("length");

                    b.HasKey("Id");

                    b.HasIndex("FileCollectionId");

                    b.ToTable("images");
                });

            modelBuilder.Entity("MessageList.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MessageGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("related_message_group");

                    b.Property<string>("Text")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageGroupId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("MessageList.Models.MessageGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("related_user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("message_groups");
                });

            modelBuilder.Entity("MessageList.Models.OtherFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasMaxLength(10500000)
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<int>("FileCollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("related_file_collection_id");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long>("Length")
                        .HasColumnType("bigint")
                        .HasColumnName("length");

                    b.HasKey("Id");

                    b.HasIndex("FileCollectionId");

                    b.ToTable("files");
                });

            modelBuilder.Entity("MessageList.Models.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("MessageList.Models.Roles.RolesToUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("related_role_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("related_user_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("roles_to_users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoleId = 2,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MessageList.Models.UrlPreview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("related_message_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("url_previews");
                });

            modelBuilder.Entity("MessageList.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<bool>("IsGreeted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_greeted");

                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("change_password_key");

                    b.Property<int>("MessagesToLoadAmount")
                        .HasColumnType("integer")
                        .HasColumnName("messages_to_load_amount");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 3, 19, 16, 1, 27, 961, DateTimeKind.Local).AddTicks(183),
                            Email = "admin@admin.com",
                            IsGreeted = false,
                            Key = "",
                            MessagesToLoadAmount = 30,
                            Password = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
                        });
                });

            modelBuilder.Entity("MessageList.Models.UserRequestInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<bool>("IsMobile")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mobile");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("RegionName")
                        .HasColumnType("text")
                        .HasColumnName("region_name");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("request_date");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("user_requests_history");
                });

            modelBuilder.Entity("MessageList.Models.VideoFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasMaxLength(105000000)
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<int>("FileCollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("related_file_collection_id");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long>("Length")
                        .HasColumnType("bigint")
                        .HasColumnName("length");

                    b.HasKey("Id");

                    b.HasIndex("FileCollectionId");

                    b.ToTable("video");
                });

            modelBuilder.Entity("MessageList.Models.AudioFile", b =>
                {
                    b.HasOne("MessageList.Models.FileCollection", "FileCollection")
                        .WithMany("Audio")
                        .HasForeignKey("FileCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileCollection");
                });

            modelBuilder.Entity("MessageList.Models.FileCollection", b =>
                {
                    b.HasOne("MessageList.Models.Message", "Message")
                        .WithOne("FileCollection")
                        .HasForeignKey("MessageList.Models.FileCollection", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MessageList.Models.ImageFile", b =>
                {
                    b.HasOne("MessageList.Models.FileCollection", "FileCollection")
                        .WithMany("Images")
                        .HasForeignKey("FileCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileCollection");
                });

            modelBuilder.Entity("MessageList.Models.Message", b =>
                {
                    b.HasOne("MessageList.Models.MessageGroup", "MessageGroup")
                        .WithMany("Messages")
                        .HasForeignKey("MessageGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageGroup");
                });

            modelBuilder.Entity("MessageList.Models.MessageGroup", b =>
                {
                    b.HasOne("MessageList.Models.User", "User")
                        .WithMany("MessageGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessageList.Models.OtherFile", b =>
                {
                    b.HasOne("MessageList.Models.FileCollection", "FileCollection")
                        .WithMany("Files")
                        .HasForeignKey("FileCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileCollection");
                });

            modelBuilder.Entity("MessageList.Models.Roles.RolesToUsers", b =>
                {
                    b.HasOne("MessageList.Models.Roles.Role", "Role")
                        .WithMany("RolesToUsers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessageList.Models.User", "User")
                        .WithMany("RolesToUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessageList.Models.UrlPreview", b =>
                {
                    b.HasOne("MessageList.Models.Message", "Message")
                        .WithMany("UrlPreviews")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MessageList.Models.VideoFile", b =>
                {
                    b.HasOne("MessageList.Models.FileCollection", "FileCollection")
                        .WithMany("Video")
                        .HasForeignKey("FileCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileCollection");
                });

            modelBuilder.Entity("MessageList.Models.FileCollection", b =>
                {
                    b.Navigation("Audio");

                    b.Navigation("Files");

                    b.Navigation("Images");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("MessageList.Models.Message", b =>
                {
                    b.Navigation("FileCollection");

                    b.Navigation("UrlPreviews");
                });

            modelBuilder.Entity("MessageList.Models.MessageGroup", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MessageList.Models.Roles.Role", b =>
                {
                    b.Navigation("RolesToUsers");
                });

            modelBuilder.Entity("MessageList.Models.User", b =>
                {
                    b.Navigation("MessageGroups");

                    b.Navigation("RolesToUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
